"""empty message

Revision ID: f8432bdadae0
Revises: 
Create Date: 2024-09-04 12:10:44.851036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8432bdadae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('c_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('channel_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('members',
    sa.Column('m_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.c_id'], ),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.c_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('members')
    op.drop_table('channel')
    # ### end Alembic commands ###
