# Use an official Java runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container
COPY target/message-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 5002

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

